/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CircularsRouteImport } from './routes/circulars'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularsRoute = CircularsRouteImport.update({
  id: '/circulars',
  path: '/circulars',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/board': typeof BoardRoute
  '/circulars': typeof CircularsRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/refund': typeof RefundRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/vision-mission': typeof VisionMissionRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/board': typeof BoardRoute
  '/circulars': typeof CircularsRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/refund': typeof RefundRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/vision-mission': typeof VisionMissionRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/board': typeof BoardRoute
  '/circulars': typeof CircularsRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/privacy': typeof PrivacyRoute
  '/publications': typeof PublicationsRoute
  '/refund': typeof RefundRoute
  '/results': typeof ResultsRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/vision-mission': typeof VisionMissionRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/board'
    | '/circulars'
    | '/contact'
    | '/curriculum'
    | '/downloads'
    | '/gallery'
    | '/history'
    | '/privacy'
    | '/publications'
    | '/refund'
    | '/results'
    | '/terms'
    | '/videos'
    | '/vision-mission'
    | '/news/$slug'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/board'
    | '/circulars'
    | '/contact'
    | '/curriculum'
    | '/downloads'
    | '/gallery'
    | '/history'
    | '/privacy'
    | '/publications'
    | '/refund'
    | '/results'
    | '/terms'
    | '/videos'
    | '/vision-mission'
    | '/news/$slug'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/board'
    | '/circulars'
    | '/contact'
    | '/curriculum'
    | '/downloads'
    | '/gallery'
    | '/history'
    | '/privacy'
    | '/publications'
    | '/refund'
    | '/results'
    | '/terms'
    | '/videos'
    | '/vision-mission'
    | '/news/$slug'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  BoardRoute: typeof BoardRoute
  CircularsRoute: typeof CircularsRoute
  ContactRoute: typeof ContactRoute
  CurriculumRoute: typeof CurriculumRoute
  DownloadsRoute: typeof DownloadsRoute
  GalleryRoute: typeof GalleryRoute
  HistoryRoute: typeof HistoryRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicationsRoute: typeof PublicationsRoute
  RefundRoute: typeof RefundRoute
  ResultsRoute: typeof ResultsRoute
  TermsRoute: typeof TermsRoute
  VideosRoute: typeof VideosRoute
  VisionMissionRoute: typeof VisionMissionRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulars': {
      id: '/circulars'
      path: '/circulars'
      fullPath: '/circulars'
      preLoaderRoute: typeof CircularsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  BoardRoute: BoardRoute,
  CircularsRoute: CircularsRoute,
  ContactRoute: ContactRoute,
  CurriculumRoute: CurriculumRoute,
  DownloadsRoute: DownloadsRoute,
  GalleryRoute: GalleryRoute,
  HistoryRoute: HistoryRoute,
  PrivacyRoute: PrivacyRoute,
  PublicationsRoute: PublicationsRoute,
  RefundRoute: RefundRoute,
  ResultsRoute: ResultsRoute,
  TermsRoute: TermsRoute,
  VideosRoute: VideosRoute,
  VisionMissionRoute: VisionMissionRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
